language: node_js
cache:
  directories:
    - ~/.npm
notifications:
  email: false
node_js:
  - 'node'
deploy:
  provider: script
  skip_cleanup: true
  script:
    - npm run build
    - npx semantic-release
