language: node_js
cache:
  directories:
    - ~/.npm
notifications:
  email: false
node_js:
  - 'node'
script:
  - npm run test
  - npm run build
before_deploy:
- echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" >> .npmrc
deploy:
  provider: script
  skip_cleanup: true
  script:
    - npx semantic-release
